/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To prevent server code from being bundled unnecessarily, this file should
 * not be imported directly. It is regenerated by `npx convex dev`.
 */
import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 */
export const api = anyApi;

/**
 * A utility for referencing Convex internal functions in your app's API.
 */
export const internal = anyApi;
