/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To prevent server code from being bundled unnecessarily, this file should
 * not be imported directly. It is regenerated by `npx convex dev`.
 */
import {
  actionGeneric,
  httpActionGeneric,
  mutationGeneric,
  queryGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";

/**
 * Define a query in this Convex deployment's public API.
 */
export const query = queryGeneric;

/**
 * Define a mutation in this Convex deployment's public API.
 */
export const mutation = mutationGeneric;

/**
 * Define an action in this Convex deployment's public API.
 */
export const action = actionGeneric;

/**
 * Define a Convex HTTP action.
 */
export const httpAction = httpActionGeneric;

/**
 * Define a query that can only be called internally, not from the client.
 */
export const internalQuery = internalQueryGeneric;

/**
 * Define a mutation that can only be called internally, not from the client.
 */
export const internalMutation = internalMutationGeneric;

/**
 * Define an action that can only be called internally, not from the client.
 */
export const internalAction = internalActionGeneric;
